logging.level.com.example=DEBUG

#HH
refresh.token=USERSQMHG7DQVKN7NS3393IIH5IMKB2TLP64QK71DINC9AMB5R7M0LVFJBL97ATQ
content.type=application/json
client.id=UHPUD43K37N4JMEN2L63B1AD41OP0IJVQT8DFB4A73UNOQ1CBUT0M04ICN7F45VN
client.secret=MSH1HSM1MN1CB0E65QU99ESB02MRNRC4UM1LKQTTH9LOQG84NR7FOJGIU2J82OQE
refreshtoken.url=https://api.hh.ru/token
redirect.url=https://macygabr.github.io/hh/callback
negotiations.url=https://api.hh.ru/negotiations

#DB
spring.datasource.url=jdbc:postgresql://34.168.159.50:5432/hh
spring.datasource.username=postgres
spring.datasource.password=macygabr
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Kafka
kafka.bootstrap-servers=37.194.168.90:9092
kafka.group-id=auth_service
kafka.auth-response-topic=auth_response
